name: ebozor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  flutter_bloc: ^9.1.1
  dio: ^5.8.0+1
  carousel_slider: ^5.1.1
  firebase_core: ^3.15.1
  cloud_firestore: ^5.6.11
  image_picker: ^1.1.2
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
