// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAay8ZRWefiJF27xsVr1U2MjQctpzJuSU0',
    appId: '1:456173619653:web:4b135142aa6ca25a9ae3ac',
    messagingSenderId: '456173619653',
    projectId: 'obozor-iyul11',
    authDomain: 'obozor-iyul11.firebaseapp.com',
    storageBucket: 'obozor-iyul11.firebasestorage.app',
    measurementId: 'G-P99SCCVVRW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvjmsnyE6aYpvF2LmzD8FMdlklViEN89g',
    appId: '1:456173619653:android:874a22e5f2e9aea09ae3ac',
    messagingSenderId: '456173619653',
    projectId: 'obozor-iyul11',
    storageBucket: 'obozor-iyul11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlTD_mGG03O2T-Tx8YfMsPv4tR3huAyrY',
    appId: '1:456173619653:ios:5a67df2dbb00ef8f9ae3ac',
    messagingSenderId: '456173619653',
    projectId: 'obozor-iyul11',
    storageBucket: 'obozor-iyul11.firebasestorage.app',
    iosBundleId: 'uz.ebozor.ebozor',
  );
}
