// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeZEmbtQr7oHZyjTnChltR39XsxjgYS5s',
    appId: '1:359601582995:web:e369489011614f98132e66',
    messagingSenderId: '359601582995',
    projectId: 'ebozor-iyul18',
    authDomain: 'ebozor-iyul18.firebaseapp.com',
    storageBucket: 'ebozor-iyul18.firebasestorage.app',
    measurementId: 'G-TMTWLNYCBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY0GwKhaOeC0g3eD_XDX2bLWW0bf8tjgQ',
    appId: '1:359601582995:android:f548b205f22e491e132e66',
    messagingSenderId: '359601582995',
    projectId: 'ebozor-iyul18',
    storageBucket: 'ebozor-iyul18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB2-Iu-UXGC_OoSb-cnJmmH5aNxA0ucbs',
    appId: '1:359601582995:ios:fdcf61ab675f7f9b132e66',
    messagingSenderId: '359601582995',
    projectId: 'ebozor-iyul18',
    storageBucket: 'ebozor-iyul18.firebasestorage.app',
    iosBundleId: 'uz.ebozor.ebozor',
  );
}
